FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install --no-cache-dir requests

RUN useradd -m appuser
USER appuser

COPY Weather /app/Weather

ENTRYPOINT ["python", "Weather/EV_W.py"]